TrajectoryPlannerROS:

  holonomic_robot: true

  acc_lim_x: 4
  acc_lim_y: 4
  acc_lim_theta: 4

  max_vel_x: 0.5
  min_vel_x: 0.2
  max_vel_y: 0.4
  max_vel_theta: 1.7
  min_in_place_vel_theta: 0.05
  escape_vel: -0.5  
  oscillation_reset_dist: 0.1 
  
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  sim_time: 1.0
  meter_scoring: true 
  latch_xy_goal_tolerance: false
  heading_scoring_timestep: 0.7
  pdist_scale: 0.8
  gdist_scale: 1.0
